image: gitpod/workspace-bun

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - env:
      KEYSTATIC: true
    init:
      | # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
      bun upgrade
      bun install --frozen-lockfile
    command: bun run dev

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Astro
    description: Port 4321 for Astro
    port: 4321
    onOpen: open-browser

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
vscode:
  extensions:
    - astro-build.astro-vscode
    - GitHub.vscode-github-actions
    - mattpocock.ts-error-translator
    - bradlc.vscode-tailwindcss
    - GraphQL.vscode-graphql
