tasks:
  command-0:
    command: |-
      export KEYSTATIC=true
      bun run dev
    dependsOn:
      - init-000
    description: init task migrated from .gitpod.yml
    name: 'Task 0: command'
    triggeredBy:
      - postDevcontainerStart
  init-000:
    command: |
      export KEYSTATIC=true
      bun install --frozen-lockfile
    description: init task migrated from .gitpod.yml
    name: 'Task 0: init'
